### ISSUE TITLE
If an image is inserted at the very first line - the top resize menu is inaccessible (hidden under menu bar)

### ISSUE THREAD

**Issue by fylzero** [portive/quill-images#4]
<img width="438" alt="Cursor_and_Portive_Quill_Images_Demo" src="https://github.com/portive/quill-images/assets/3542501/e88281e3-7cb0-43a0-a413-f86a6af230a4">

**Comment by thesunny** [comment]
Thanks fylzero! Nice catch.

**Comment by thesunny** [comment]
Hi @fylzero, this issue should be resolved now. Thank you!
